// Builds web/miliastra-search.bundle.js: the whole engine (src/web.mjs and everything it imports) plus the data files
// as ONE classic script, so miliastra-search.htm works when opened straight from disk. Browsers refuse ES modules and
// fetch() on file:// pages, which is why the modules are folded into a single file here instead of being loaded as is.
//
// This is a deliberately tiny bundler that understands only the import/export forms the engine uses (named imports,
// `export function|const|class|let`); anything else makes it fail loudly rather than produce a broken bundle.
// No npm dependencies, same as the rest of the project. `npm run build-web` rewrites the bundle;
// test/web.test.mjs fails when the committed bundle is stale.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs, UsageError } from './cli-args.mjs';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = 'src/web.mjs';
const OUT = 'web/miliastra-search.bundle.js';
const GLOBAL = 'MiliastraSearch';
const VIRTUAL = 'miliastra:resources';
const DATA_DIRS = [['data', /\.json$/], ['schema', /\.proto$/]];

const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8').replace(/^\uFEFF/, '');

function resources() {
  const r = {};
  for (const [dir, re] of DATA_DIRS) for (const n of fs.readdirSync(path.join(root, dir)).sort()) if (re.test(n)) r[`${dir}/${n}`] = read(`${dir}/${n}`);
  return r;
}

/** One module -> { code (body that fills `exports`), deps: [rel paths] } */
function transform(rel, src) {
  const deps = [];
  const dir = path.posix.dirname(rel);
  const resolve = (spec) => {
    if (spec === VIRTUAL) return VIRTUAL;
    if (!spec.startsWith('.')) throw new Error(`${rel}: cannot bundle import of "${spec}" (only relative modules; Node built-ins belong in host-node.mjs)`);
    return path.posix.normalize(path.posix.join(dir, spec));
  };
  let code = src.replace(/^import\s*\{([^}]*)\}\s*from\s*'([^']+)';?[ \t]*$/gm, (_, names, spec) => {
    const id = resolve(spec); deps.push(id);
    const list = names.split(',').map((x) => x.trim()).filter(Boolean).map((x) => x.replace(/^(\S+)\s+as\s+(\S+)$/, '$1: $2'));
    return `const { ${list.join(', ')} } = __req(${JSON.stringify(id)});`;
  });
  code = code.replace(/^import\s+'([^']+)';?[ \t]*$/gm, (_, spec) => { const id = resolve(spec); deps.push(id); return `__req(${JSON.stringify(id)});`; });
  const names = [];
  code = code.replace(/^export\s+((?:async\s+)?function\*?|const|let|class)\s+([A-Za-z_$][\w$]*)/gm, (_, kw, name) => { names.push(name); return `${kw} ${name}`; });
  code = code.replace(/^export\s*\{([^}]*)\}\s*;?[ \t]*$/gm, (_, list) => { for (const x of list.split(',').map((s) => s.trim()).filter(Boolean)) names.push(x); return ''; });
  const bad = code.split('\n').findIndex((l) => /^\s*(import|export)\b(?!\s*[:=(.,])/.test(l) && !/^\s*(\/\/|\*)/.test(l));
  if (bad >= 0) throw new Error(`${rel}:${bad + 1}: unsupported import/export syntax: ${code.split('\n')[bad].trim()}`);
  if (/\bimport\.meta\b|\brequire\(|\bprocess\.|\bBuffer\b/.test(code.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, ''))) {
    throw new Error(`${rel}: Node-specific code (import.meta / require / process / Buffer) in a bundled module; route it through src/host.mjs`);
  }
  // `exports` is filled at the end: function declarations are hoisted, and the engine has no import cycles (checked below).
  return { code: code + `\n__exports(${JSON.stringify(names)}, { ${names.join(', ')} });`, deps };
}

export function buildBundle() {
  const modules = new Map(); // rel -> code, in dependency order
  const visiting = new Set();
  const visit = (rel) => {
    if (modules.has(rel) || rel === VIRTUAL) return;
    if (visiting.has(rel)) throw new Error(`import cycle through ${rel}: the bundler binds imports once, cycles are not supported`);
    visiting.add(rel);
    const { code, deps } = transform(rel, read(rel));
    deps.forEach(visit);
    visiting.delete(rel);
    modules.set(rel, code);
  };
  visit(ENTRY);
  const defs = [...modules].map(([rel, code]) => `${JSON.stringify(rel)}: function (__req, __exports) {\n${code}\n}`).join(',\n');
  return `// GENERATED by scripts/build-web.mjs from src/ + data/ + schema/ – do not edit; run: npm run build-web
(function () {
'use strict';
const __defs = {
${defs}
};
const __cache = { ${JSON.stringify(VIRTUAL)}: { RESOURCES: ${JSON.stringify(resources())} } };
function __req(id) {
  if (__cache[id]) return __cache[id];
  const ex = (__cache[id] = {});
  __defs[id](__req, (names, obj) => { for (const n of names) ex[n] = obj[n]; });
  return ex;
}
globalThis.${GLOBAL} = __req(${JSON.stringify(ENTRY)});
})();
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const USAGE = 'usage: npm run build-web   (node scripts/build-web.mjs)\nRewrites web/miliastra-search.bundle.js from src/, data/ and schema/. Takes no arguments.\n';
  let parsed;
  try { parsed = parseArgs(process.argv.slice(2)); } catch (e) {
    if (!(e instanceof UsageError)) throw e;
    console.error(`error: ${e.message}\n\n${USAGE}`);
    process.exit(2);
  }
  if (parsed.help) process.stdout.write(USAGE);
  else {
    const text = buildBundle();
    fs.mkdirSync(path.join(root, path.dirname(OUT)), { recursive: true });
    fs.writeFileSync(path.join(root, OUT), text);
    console.log(`${OUT}: ${(text.length / 1024).toFixed(0)} KB`);
  }
}
